import { NextRequest, NextResponse } from 'next/server'
import OpenAI from 'openai'

function getOpenAI() {
  if (!process.env.OPENAI_API_KEY) {
    throw new Error('OPENAI_API_KEY environment variable is not set')
  }
  return new OpenAI({
    apiKey: process.env.OPENAI_API_KEY,
  })
}

interface GenerateSpecRequest {
  mode: 'ai' | 'manual'
  name: string
  description: string
  rawText?: string // For AI mode
  pages?: Array<{ // For manual mode
    title: string
    description: string
  }>
}

export async function POST(request: NextRequest) {
  try {
    const body: GenerateSpecRequest = await request.json()
    const { mode, name, description, rawText, pages } = body

    if (!name || !description) {
      return NextResponse.json(
        { success: false, error: 'Name and description are required' },
        { status: 400 }
      )
    }

    let proposalJson: any

    if (mode === 'ai') {
      if (!rawText) {
        return NextResponse.json(
          { success: false, error: 'Raw text is required for AI mode' },
          { status: 400 }
        )
      }

      // Call OpenAI to generate proposal
      const openai = getOpenAI()
      const model = process.env.OPENAI_MODEL || 'gpt-4o-mini'

      const prompt = `You are a SharePoint content proposal generator. 
Based on the user's description, create a SharePoint site proposal.

User Description:
"${rawText}"

Generate a JSON proposal with this exact structure:
{
  "title": "SharePoint Content Proposal: [appropriate title]",
  "executiveSummary": "[2-3 sentence summary of the SharePoint build]",
  "contentPages": [
    {
      "pageNumber": 1,
      "title": "[Page title]",
      "description": "[Detailed description of what this page contains]"
    }
  ],
  "conclusion": "[1-2 sentence conclusion]"
}

Infer the number of pages needed from the description. Each page should have a clear purpose and description.
Return ONLY valid JSON, no markdown formatting.`

      const response = await openai.chat.completions.create({
        model,
        messages: [
          { role: 'system', content: 'You are a SharePoint content proposal generator. Always return valid JSON.' },
          { role: 'user', content: prompt },
        ],
        response_format: { type: 'json_object' },
        temperature: 0.7,
      })

      const content = response.choices[0].message.content
      if (!content) {
        return NextResponse.json(
          { success: false, error: 'No content generated by OpenAI' },
          { status: 500 }
        )
      }

      try {
        proposalJson = JSON.parse(content)
      } catch (parseError) {
        console.error('Failed to parse OpenAI response:', parseError)
        return NextResponse.json(
          { success: false, error: 'Failed to parse AI response as JSON' },
          { status: 500 }
        )
      }
    } else {
      // Manual mode - construct JSON from pages
      if (!pages || pages.length === 0) {
        return NextResponse.json(
          { success: false, error: 'At least one page is required for manual mode' },
          { status: 400 }
        )
      }

      proposalJson = {
        title: `SharePoint Content Proposal: ${name}`,
        executiveSummary: description,
        contentPages: pages.map((page, index) => ({
          pageNumber: index + 1,
          title: page.title,
          description: page.description,
        })),
        conclusion: `This SharePoint site will serve as ${description.toLowerCase()}.`,
      }
    }

    // Return the spec
    return NextResponse.json({
      success: true,
      spec: {
        name,
        description,
        rawJson: JSON.stringify(proposalJson, null, 2),
      },
    })
  } catch (error: any) {
    console.error('Failed to generate SharePoint spec:', error)
    
    if (error.message?.includes('OPENAI_API_KEY')) {
      return NextResponse.json(
        { success: false, error: 'OpenAI API key is not configured' },
        { status: 500 }
      )
    }

    return NextResponse.json(
      { success: false, error: error.message || 'Failed to generate spec' },
      { status: 500 }
    )
  }
}
