'use client'

import { useState, useEffect } from 'react'
import { useRouter } from 'next/navigation'
import { getAuth } from 'firebase/auth'
import api from '@/lib/api'
import { refreshWorkMe } from '@/lib/workme.client'
import { User, ArrowLeft } from 'lucide-react'

export default function ProfilePage() {
  const router = useRouter()
  const [loading, setLoading] = useState(false)
  const [workMeId, setWorkMeId] = useState<string | null>(null)
  const [email, setEmail] = useState<string>('')
  const [photoURL, setPhotoURL] = useState<string>('')
  
  // WorkMe model fields only
  const [formData, setFormData] = useState({
    headline: '',
    handle: '',
    title: '',
    linkedinUrl: '',
  })

  useEffect(() => {
    if (typeof window !== 'undefined') {
      const id = localStorage.getItem('workMeId')
      if (!id) {
        router.push('/signin')
        return
      }
      setWorkMeId(id)
      
      // Get email and photo from Firebase
      const firebaseUser = getAuth().currentUser
      if (firebaseUser) {
        setEmail(firebaseUser.email || '')
        setPhotoURL(firebaseUser.photoURL || '')
      }
      
      loadProfile()
    }
  }, [router])

  const loadProfile = async () => {
    try {
      const response = await api.get('/api/workme/me')
      const workMe = response.data?.workMe
      const firebaseUser = getAuth().currentUser
      
      if (firebaseUser?.email) {
        setEmail(firebaseUser.email)
      }
      if (firebaseUser?.photoURL) {
        setPhotoURL(firebaseUser.photoURL)
      }
      
      if (workMe) {
        // Clear auto-generated handles (user_* or temp_*) so user can enter their own
        const handleValue = workMe.handle || ''
        const isAutoGenerated = handleValue.startsWith('user_') || handleValue.startsWith('temp_')
        
        setFormData({
          headline: workMe.headline || '',
          handle: isAutoGenerated ? '' : handleValue,
          title: workMe.title || '',
          linkedinUrl: workMe.linkedinUrl || '',
        })
      }
    } catch (error) {
      console.log('Profile not loaded:', error)
    }
  }

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault()
    if (!workMeId || loading) return

    // Validate required fields
    if (!formData.headline.trim() || !formData.handle.trim()) {
      alert('Please fill in headline and handle (required)')
      return
    }

    setLoading(true)
    try {
      await api.put('/api/workme/me', {
        headline: formData.headline || null,
        handle: formData.handle,
        title: formData.title || null,
        linkedinUrl: formData.linkedinUrl || null,
      })

      // Refresh WorkMe in localStorage after profile update
      await refreshWorkMe()

      // Check if user has a company, if not redirect to company setup
      const profileResponse = await api.get('/api/workme/me')
      const hasCompany = profileResponse.data?.workMe?.companyId

      if (hasCompany) {
        router.push('/dashboard')
      } else {
        router.push('/setup/company')
      }
    } catch (error: any) {
      console.error('Profile update failed:', error)
      alert(`Failed to update profile: ${error.response?.data?.error || error.message || 'Please try again.'}`)
    } finally {
      setLoading(false)
    }
  }

  if (!workMeId) {
    return (
      <div className="min-h-screen flex items-center justify-center bg-white">
        <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-sky-500"></div>
      </div>
    )
  }

  return (
    <div className="min-h-screen bg-white flex items-center justify-center p-4">
      <div className="max-w-2xl w-full bg-white rounded-lg p-8 shadow-lg border-2 border-sky-500">
        {/* Go Back Button */}
        <button
          onClick={() => router.push('/dashboard')}
          className="mb-6 flex items-center text-gray-600 hover:text-gray-900 transition"
        >
          <ArrowLeft className="h-4 w-4 mr-2" />
          <span className="text-sm font-medium">Go Back to Dashboard</span>
        </button>

        {/* Header with icon */}
        <div className="mb-8 text-center">
          <div className="inline-flex items-center justify-center w-16 h-16 bg-sky-100 rounded-full mb-4 overflow-hidden">
            {photoURL ? (
              <img 
                src={photoURL} 
                alt="Profile" 
                className="w-full h-full object-cover"
                onError={(e) => {
                  e.currentTarget.style.display = 'none'
                  const icon = e.currentTarget.nextElementSibling as HTMLElement
                  if (icon) icon.style.display = 'block'
                }}
              />
            ) : null}
            <User className={`h-8 w-8 text-sky-600 ${photoURL ? 'hidden' : ''}`} />
          </div>
          <h1 className="text-3xl font-bold text-gray-900 mb-2">
            Your Profile
          </h1>
          <p className="text-gray-600">
            Update your WorkMe identity
          </p>
        </div>

        {/* Profile Form */}
        <form onSubmit={handleSubmit} className="space-y-6">
          {/* Email (read-only, from Firebase) */}
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-2">
              Email
            </label>
            <input
              type="email"
              value={email}
              disabled
              className="w-full px-4 py-3 bg-gray-50 border border-gray-300 rounded-lg text-gray-600 cursor-not-allowed"
            />
            <p className="text-xs text-gray-500 mt-1">Email from your Firebase account (read-only)</p>
          </div>

          <div>
            <label className="block text-sm font-medium text-gray-700 mb-2">
              Headline *
            </label>
            <input
              type="text"
              required
              value={formData.headline}
              onChange={(e) => setFormData({ ...formData, headline: e.target.value })}
              className="w-full px-4 py-3 bg-white border border-gray-300 rounded-lg text-gray-900 placeholder-gray-400 focus:outline-none focus:ring-2 focus:ring-sky-500 focus:border-sky-500"
              placeholder="e.g. Marketing Manager | Growth Strategist"
            />
            <p className="text-xs text-gray-500 mt-1">Professional headline</p>
          </div>

          <div>
            <label className="block text-sm font-medium text-gray-700 mb-2">
              Handle (Username) *
            </label>
            <input
              type="text"
              required
              value={formData.handle}
              onChange={(e) => {
                // Only allow lowercase letters, numbers, and underscores
                const sanitized = e.target.value.toLowerCase().replace(/[^a-z0-9_]/g, '')
                setFormData({ ...formData, handle: sanitized })
              }}
              className="w-full px-4 py-3 bg-white border border-gray-300 rounded-lg text-gray-900 placeholder-gray-400 focus:outline-none focus:ring-2 focus:ring-sky-500 focus:border-sky-500"
              placeholder="e.g. johndoe or adam_cole"
            />
            <p className="text-xs text-gray-500 mt-1">Choose your unique username (letters, numbers, and underscores only)</p>
          </div>

          <div>
            <label className="block text-sm font-medium text-gray-700 mb-2">
              Title (Optional)
            </label>
            <input
              type="text"
              value={formData.title}
              onChange={(e) => setFormData({ ...formData, title: e.target.value })}
              className="w-full px-4 py-3 bg-white border border-gray-300 rounded-lg text-gray-900 placeholder-gray-400 focus:outline-none focus:ring-2 focus:ring-sky-500 focus:border-sky-500"
              placeholder="e.g. Senior Marketing Manager"
            />
          </div>

          <div>
            <label className="block text-sm font-medium text-gray-700 mb-2">
              LinkedIn URL (Optional)
            </label>
            <input
              type="url"
              value={formData.linkedinUrl}
              onChange={(e) => setFormData({ ...formData, linkedinUrl: e.target.value })}
              className="w-full px-4 py-3 bg-white border border-gray-300 rounded-lg text-gray-900 placeholder-gray-400 focus:outline-none focus:ring-2 focus:ring-sky-500 focus:border-sky-500"
              placeholder="https://linkedin.com/in/yourprofile"
            />
          </div>

          <div className="flex gap-4 pt-4">
            <button
              type="button"
              onClick={() => router.push('/dashboard')}
              className="px-6 py-3 border border-gray-300 text-gray-700 rounded-lg font-semibold hover:bg-gray-50 transition"
            >
              Go Back
            </button>
            <button
              type="submit"
              disabled={loading}
              className="flex-1 bg-sky-600 text-white py-3 px-6 rounded-lg font-semibold hover:bg-sky-700 transition shadow-md disabled:opacity-50 disabled:cursor-not-allowed"
            >
              {loading ? 'Saving...' : 'Save Profile'}
            </button>
          </div>
        </form>
      </div>
    </div>
  )
}
